"""Merge source JSON files under data/ into data/dataSet.json, then shard by grid.

Outputs:
  data/dataSet.json              — full merge (source of truth for tooling)
  data/dist/manifest.json        — cellSize, counts, cell keys
  data/dist/index.slim.json      — id/lat/lng/type for all places
  data/dist/cells/{i}_{j}.json   — full records per ~2 km cell
  web/public/places/…            — same tree for Vite static fetch
  mobile/assets/places/…         — same tree + generated cellRegistry.js
"""

from __future__ import annotations

import json
import shutil
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
OUT_PATH = DATA_DIR / "dataSet.json"
DIST_DIR = DATA_DIR / "dist"
WEB_PLACES = ROOT / "web" / "public" / "places"
MOBILE_PLACES = ROOT / "mobile" / "assets" / "places"
MOBILE_REGISTRY = ROOT / "mobile" / "src" / "data" / "cellRegistry.js"

SOURCE_FILES = [
    "711_with_toilet.json",
    "louisa_stores.json",
]

REQUIRED = ("id", "type", "地址", "lat", "lng", "營業時間")

# ~0.02° ≈ 2 km in Taiwan; must match app2/shared/places.js
CELL_SIZE = 0.02

sys.path.insert(0, str(Path(__file__).resolve().parent))
from hours import normalize_hours  # noqa: E402


def load_source(path: Path) -> list[dict]:
    if not path.exists():
        print(f"skip missing: {path.name}")
        return []
    with open(path, encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        raise ValueError(f"{path.name} must be a JSON array")
    return data


def coerce_hours(value) -> dict:
    if isinstance(value, dict) and "byDay" in value:
        return {
            "raw": str(value.get("raw") or ""),
            "allDay": bool(value.get("allDay")),
            "unknown": bool(value.get("unknown")),
            "byDay": value.get("byDay") or {},
        }
    return normalize_hours(str(value or ""))


def normalize(item: dict) -> dict | None:
    for key in REQUIRED:
        if key not in item:
            print(f"skip incomplete record (missing {key}): {item.get('地址')}")
            return None
    return {
        "id": str(item["id"]),
        "type": str(item["type"]),
        "name": str(item.get("name") or ""),
        "地址": str(item["地址"]),
        "lat": float(item["lat"]),
        "lng": float(item["lng"]),
        "營業時間": coerce_hours(item["營業時間"]),
        "備註": list(item.get("備註") or []),
    }


def cell_key(lat: float, lng: float) -> str:
    return f"{int(lat // CELL_SIZE)}_{int(lng // CELL_SIZE)}"


def write_json(path: Path, data) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")


def reset_dir(path: Path) -> None:
    if path.exists():
        shutil.rmtree(path)
    path.mkdir(parents=True, exist_ok=True)


def write_shards(places: list[dict]) -> dict:
    slim: list[dict] = []
    buckets: dict[str, list[dict]] = defaultdict(list)

    for p in places:
        slim.append(
            {
                "id": p["id"],
                "lat": round(p["lat"], 5),
                "lng": round(p["lng"], 5),
                "type": p["type"],
            }
        )
        buckets[cell_key(p["lat"], p["lng"])].append(p)

    reset_dir(DIST_DIR / "cells")
    for key, rows in sorted(buckets.items()):
        write_json(DIST_DIR / "cells" / f"{key}.json", rows)

    write_json(DIST_DIR / "index.slim.json", slim)

    manifest = {
        "cellSize": CELL_SIZE,
        "placeCount": len(places),
        "cellCount": len(buckets),
        "cells": sorted(buckets.keys()),
    }
    write_json(DIST_DIR / "manifest.json", manifest)
    return manifest


def sync_tree(src: Path, dest: Path) -> None:
    if dest.exists():
        shutil.rmtree(dest)
    shutil.copytree(src, dest)


def write_mobile_registry(cell_keys: list[str]) -> None:
    lines = [
        "/* AUTO-GENERATED by fetchData/buildDataSet.py — do not edit */",
        "/* Offline fallback when EXPO_PUBLIC_PLACES_URL is unset */",
        "",
        "const loaders = {",
    ]
    for key in cell_keys:
        lines.append(f"  '{key}': () => require('../../assets/places/cells/{key}.json'),")
    lines.extend(
        [
            "};",
            "",
            "export function loadCellSync(key) {",
            "  const load = loaders[key];",
            "  if (!load) return [];",
            "  const rows = load();",
            "  return Array.isArray(rows) ? rows : [];",
            "}",
            "",
            "export const CELL_KEYS = Object.keys(loaders);",
            "",
        ]
    )
    MOBILE_REGISTRY.parent.mkdir(parents=True, exist_ok=True)
    MOBILE_REGISTRY.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    merged: list[dict] = []
    seen: set[str] = set()

    for name in SOURCE_FILES:
        for item in load_source(DATA_DIR / name):
            normalized = normalize(item)
            if normalized is None:
                continue
            if normalized["id"] in seen:
                continue
            seen.add(normalized["id"])
            merged.append(normalized)

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(json.dumps(merged, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"wrote {len(merged)} places → {OUT_PATH}")

    manifest = write_shards(merged)
    print(
        f"wrote shards → {DIST_DIR} "
        f"({manifest['cellCount']} cells, cellSize={manifest['cellSize']})"
    )

    sync_tree(DIST_DIR, WEB_PLACES)
    print(f"synced → {WEB_PLACES}")

    sync_tree(DIST_DIR, MOBILE_PLACES)
    write_mobile_registry(manifest["cells"])
    print(f"synced → {MOBILE_PLACES}")
    print(f"wrote → {MOBILE_REGISTRY}")


if __name__ == "__main__":
    main()
